# Generated by Django 2.2.5 on 2019-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dflt.jpg', upload_to='profile_pics'),
        ),
    ]
